# Build Check Skill - Verify TypeScript build
name: build-check
description: TypeScriptビルドを実行し、コンパイルエラーを報告するスキル。npm run buildを実行してビルド結果を確認。

allowedRoles:
  - developer
  - senior-developer
  - admin

# Intent classification triggers
triggers:
  - ビルド
  - build
  - compile
  - コンパイル
  - bundle
  - tsc
  - 型チェック
  - type check

allowedTools:
  - mycelium-sandbox__bash
  - filesystem__read_file
  - filesystem__list_directory
