# Test Runner Skill - Run vitest tests
name: test-runner
description: プロジェクトのテストを実行し、結果を報告するスキル。vitestを使用してユニットテストを実行。

allowedRoles:
  - developer
  - senior-developer
  - admin
  - tester

# Intent classification triggers
triggers:
  - テスト
  - test
  - spec
  - jest
  - vitest
  - pytest
  - 検証
  - verify

allowedTools:
  - mycelium-sandbox__bash
  - filesystem__read_file
  - filesystem__list_directory
